spring.datasource.url: ${JDBC_DATABASE_URL:postgres://lruvegwwlykbyc:186cf422ba82ad7a45c80f1aa63dac00367d329ffe9f03b13b7f245658123b24@ec2-54-161-150-170.compute-1.amazonaws.com:5432/dal0kupjlr2jte}
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

spring.thymeleaf.mode=HTML

logging.level.org.springframework=INFO

spring.profiles.active=production

server.port=${PORT:5000}

# Hibernate Properties

# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.formate_sql=true



logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE
