# Generated by Django 4.1.3 on 2022-11-28 22:20

import ckeditor.fields
import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adminuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_pass', models.CharField(max_length=20)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sitedescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=500, verbose_name='Site Name')),
                ('site_also_name', models.CharField(max_length=500, verbose_name='Also Name As')),
                ('site_latitude', models.FloatField(verbose_name='Latitude')),
                ('site_longitude', models.FloatField(verbose_name='Lognitude')),
                ('site_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.category', verbose_name='Select Category')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('country_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.country', verbose_name='Select Country')),
            ],
        ),
        migrations.CreateModel(
            name='Sitevideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitevideo_name', models.CharField(max_length=500, verbose_name='Video Name')),
                ('sitevideo_url', embed_video.fields.EmbedVideoField(blank=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('site_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sitedescription', verbose_name='select Heritage Site')),
            ],
        ),
        migrations.CreateModel(
            name='Siteimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteimage_name', models.CharField(max_length=500, verbose_name='Image Name')),
                ('siteimage_url', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Upload Image')),
                ('is_banner_image', models.BooleanField(default=False, null=True)),
                ('siteimage_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('site_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sitedescription', verbose_name='select Heritage Site')),
            ],
        ),
        migrations.AddField(
            model_name='sitedescription',
            name='state_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.state', verbose_name='Select State'),
        ),
    ]
