# Generated by Django 4.1.3 on 2022-11-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='user_pass',
            field=models.CharField(max_length=264),
        ),
    ]
